name: libre_washio
description: "Car Service Booking Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  country_code_picker: ^3.0.0
  provider: ^6.1.1
  google_maps_flutter: ^2.0.0
  permission_handler: ^11.3.1
  geolocator: ^9.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Added for launcher icons
  flutter_native_splash: ^2.4.0   # Added for splash screen

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo_light.png"
  min_sdk_android: 21 # Optional: Depending on your app's min SDK
  # remove_alpha_ios: true # Uncomment if your PNG has transparency and you want a white background for iOS icon
  # web:
  #   generate: true
  #   image_path: "assets/images/logo_light.png"
  #   background_color: "#ffffff"
  #   theme_color: "#ffffff"
  # windows:
  #   generate: true
  #   image_path: "assets/images/logo_light.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "assets/images/logo_light.png"

flutter_native_splash:
  color: "#FFFFFF"  # Background color of your splash screen
  image: assets/images/logo_light.png # Path to your splash screen image
  # branding: assets/images/branding_dark.png # Optional: if you have a branding logo below your main image
  # color_dark: "#000000"
  # image_dark: assets/images/logo_light.png
  # branding_dark: assets/images/branding_dark.png

  android_12:
    image: assets/images/logo_light.png
    # icon_background_color: "#FFFFFF"
    # image_dark: assets/images/logo_light.png
    # icon_background_color_dark: "#000000"

  # fullscreen: true # Uncomment if you want a fullscreen splash screen
  # android_gravity: center
  # ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_light.jpeg
    - assets/images/logo_light.png
    - assets/images/google_logo.png
